//! The OCPI response envelope.
//!
//! Every OCPI endpoint wraps its payload in a JSON object carrying the
//! protocol `status_code`, an optional `status_message`, and the server
//! `timestamp`. This module models that envelope generically over the payload
//! type `T`.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::status::OcpiStatusCode;

/// The standard OCPI response wrapper.
///
/// The `data` field is present on success and typically omitted on error.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OcpiResponse<T> {
    /// The response payload, present on success.
    #[serde(skip_serializing_if = "Option::is_none", default = "none")]
    pub data: Option<T>,

    /// The OCPI status code (e.g. `1000` for success).
    pub status_code: u16,

    /// An optional human-readable message, usually set on error.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub status_message: Option<String>,

    /// The time at which the response was generated by the server.
    pub timestamp: DateTime<Utc>,
}

fn none<T>() -> Option<T> {
    None
}

impl<T> OcpiResponse<T> {
    /// Build a successful response (`status_code = 1000`) carrying `data`.
    #[must_use]
    pub fn success(data: T) -> Self {
        Self {
            data: Some(data),
            status_code: OcpiStatusCode::Success.code(),
            status_message: None,
            timestamp: Utc::now(),
        }
    }

    /// Build an error response with the given status code and message.
    #[must_use]
    pub fn error(code: OcpiStatusCode, message: impl Into<String>) -> Self {
        Self {
            data: None,
            status_code: code.code(),
            status_message: Some(message.into()),
            timestamp: Utc::now(),
        }
    }

    /// The recognised [`OcpiStatusCode`], if the integer code is known.
    #[must_use]
    pub fn status(&self) -> Option<OcpiStatusCode> {
        OcpiStatusCode::from_code(self.status_code)
    }

    /// `true` if the envelope reports success (`status_code = 1000`).
    #[must_use]
    pub fn is_success(&self) -> bool {
        self.status_code == OcpiStatusCode::Success.code()
    }
}

#[cfg(test)]
mod tests {
    use super::OcpiResponse;
    use crate::status::OcpiStatusCode;

    #[test]
    fn success_round_trips_through_json() {
        let resp = OcpiResponse::success(42u32);
        let json = serde_json::to_string(&resp).expect("serialize");
        let back: OcpiResponse<u32> = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.data, Some(42));
        assert!(back.is_success());
        assert_eq!(back.status(), Some(OcpiStatusCode::Success));
    }

    #[test]
    fn error_omits_data_field() {
        let resp: OcpiResponse<u32> =
            OcpiResponse::error(OcpiStatusCode::InvalidParameters, "missing country_code");
        let json = serde_json::to_string(&resp).expect("serialize");
        assert!(!json.contains("\"data\""));
        assert!(json.contains("2001"));
    }
}
