//! OCPI **2.2.1** typed models (the primary production target).
//!
//! Modules: Versions, Credentials, Locations, Sessions, CDRs, Tariffs, Tokens,
//! Commands, ChargingProfiles, HubClientInfo.
//!
//! Populated incrementally — see milestones **M2–M6** in the roadmap.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::common::{
    BusinessDetails, CiString, CiString2, CiString3, CiString36, CiString39, CiString48,
    DisplayText, EnergyMix, GeoLocation, Price, Role, Url,
};
use crate::OcpiError;

// ── CredentialsRole ───────────────────────────────────────────────────────────

/// A single role entry in a [`Credentials`] object.
///
/// Every role needs a unique combination of `role`, `party_id`, and
/// `country_code`. A platform that provides white-label CPO services may
/// carry multiple `CredentialsRole` entries — the schema is forward-compatible
/// with that use-case even though the current server implementation only
/// handles single-role registrations.
///
/// Spec: `specs/ocpi/2.2.1/credentials.asciidoc` — CredentialsRole class.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CredentialsRole {
    /// The role this party fulfils in the OCPI ecosystem.
    pub role: Role,
    /// Business details about this party.
    pub business_details: BusinessDetails,
    /// eMI3 party identifier (3-char, e.g. `"EXA"`).
    pub party_id: CiString3,
    /// ISO 3166-1 alpha-2 country code (e.g. `"NL"`).
    pub country_code: CiString2,
}

// ── Credentials ───────────────────────────────────────────────────────────────

/// The credentials object exchanged during OCPI registration (POST) and
/// updates (PUT), and returned on GET.
///
/// `roles` must be non-empty; multi-role is schema-legal per the spec.
/// Server implementations that have not yet added multi-role support
/// should call [`Credentials::check_single_role`] and return
/// [`OcpiStatusCode::ServerError`](crate::OcpiStatusCode::ServerError) on
/// failure.
///
/// Spec: `specs/ocpi/2.2.1/credentials.asciidoc` — Credentials object.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Credentials {
    /// Bearer token the remote party must use in subsequent requests.
    ///
    /// OCPI 2.2.1 spec: printable non-whitespace ASCII (U+0021–U+007E),
    /// max 64 characters. Not validated here — callers are responsible.
    pub token: String,
    /// URL of this party's `/versions` endpoint.
    pub url: Url,
    /// Roles this party provides. Non-empty; one entry is the common case.
    pub roles: Vec<CredentialsRole>,
}

impl Credentials {
    /// Returns `Err` when `roles` is empty (spec requires at least one).
    ///
    /// # Errors
    ///
    /// Returns [`OcpiError::Invalid`] if `roles` is empty.
    pub fn validate(&self) -> Result<(), OcpiError> {
        if self.roles.is_empty() {
            return Err(OcpiError::Invalid(
                "credentials.roles must contain at least one entry".into(),
            ));
        }
        Ok(())
    }

    /// Returns `Err` when `roles` has more than one entry.
    ///
    /// Call this in server implementations that have not yet added multi-role
    /// support; return [`OcpiStatusCode::ServerError`](crate::OcpiStatusCode::ServerError)
    /// to the remote party so it knows the limitation is server-side.
    ///
    /// # Errors
    ///
    /// Returns [`OcpiError::Invalid`] if `roles.len() > 1`.
    pub fn check_single_role(&self) -> Result<(), OcpiError> {
        if self.roles.len() > 1 {
            return Err(OcpiError::Invalid(
                "multi-role credentials are not yet supported by this server".into(),
            ));
        }
        Ok(())
    }
}

// ── TokenType ─────────────────────────────────────────────────────────────────

/// Type of RFID/app token used to start a session or CDR.
///
/// Forward reference — full definition lives in the Tokens module (M5).
///
/// Spec: `specs/ocpi/2.2.1/mod_tokens.asciidoc` — TokenType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TokenType {
    /// One-time-use token generated by a server or app (single session binding).
    AdHocUser,
    /// Persistent app-generated token (same user, same token every session).
    AppUser,
    /// Other token type.
    Other,
    /// RFID token read by the charge point reader.
    Rfid,
}

// ── AuthMethod ────────────────────────────────────────────────────────────────

/// Method used for authentication during a charging session or CDR.
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — AuthMethod enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AuthMethod {
    /// Authentication request was sent to the eMSP.
    AuthRequest,
    /// A Command (StartSession or ReserveNow) was used; its token was the authorization.
    Command,
    /// Whitelist was used; no real-time eMSP request was performed.
    Whitelist,
}

// ── CdrToken ──────────────────────────────────────────────────────────────────

/// Compact token record embedded in a Session or CDR.
///
/// Contains the minimum information needed to identify the token that started
/// the session. Does not include display-only fields like `visual_number` —
/// those live in the full `Token` object (Tokens module, M5).
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — CdrToken class.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CdrToken {
    /// ISO 3166-1 alpha-2 country code of the eMSP that owns this token.
    pub country_code: CiString2,
    /// Party ID of the eMSP that owns this token.
    pub party_id: CiString3,
    /// Unique identifier of the token (e.g. the RFID card UID).
    pub uid: CiString36,
    /// Type of the token.
    #[serde(rename = "type")]
    pub token_type: TokenType,
    /// Contract ID (eMA ID) of the EV driver within the eMSP's platform.
    pub contract_id: CiString36,
}

// ── CdrDimensionType ──────────────────────────────────────────────────────────

/// Measurement dimension type for a charging period.
///
/// Values marked *session-only* are valid in `Session.charging_periods` but
/// SHALL NOT appear in CDR `charging_periods`.
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — CdrDimensionType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CdrDimensionType {
    /// Average charging current (A). Session-only.
    Current,
    /// Total energy (dis-)charged (kWh).
    Energy,
    /// Total energy fed back into the grid (kWh). Session-only.
    EnergyExport,
    /// Total energy charged from the grid (kWh). Session-only.
    EnergyImport,
    /// Sum of maximum current over all phases (A).
    MaxCurrent,
    /// Sum of minimum current over all phases (A).
    MinCurrent,
    /// Maximum power reached (kW).
    MaxPower,
    /// Minimum power reached (kW).
    MinPower,
    /// Time the vehicle was not requesting power (hours).
    ParkingTime,
    /// Average power (kW). Session-only.
    Power,
    /// Time the EVSE was reserved and idle (hours).
    ReservationTime,
    /// Current state of charge of the EV (0–100 %). Session-only.
    StateOfCharge,
    /// Time actively charging (hours).
    Time,
}

// ── CdrDimension ──────────────────────────────────────────────────────────────

/// A single measured dimension within a [`ChargingPeriod`].
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — CdrDimension class.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CdrDimension {
    /// The dimension type.
    #[serde(rename = "type")]
    pub dimension_type: CdrDimensionType,
    /// Volume consumed, in the unit defined by `dimension_type`.
    pub volume: f64,
}

// ── ChargingPeriod ────────────────────────────────────────────────────────────

/// A contiguous sub-interval of a charging session with associated dimension
/// measurements. Shared between Sessions and CDRs.
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — ChargingPeriod class.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChargingPeriod {
    /// Start of this period. The period ends when the next period begins (or
    /// the session ends if this is the last period).
    pub start_date_time: DateTime<Utc>,
    /// Dimension measurements active during this period.
    pub dimensions: Vec<CdrDimension>,
    /// Tariff ID applicable to this period, if any.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tariff_id: Option<CiString36>,
}

// ── SessionStatus ─────────────────────────────────────────────────────────────

/// State of a charging session.
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — SessionStatus enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SessionStatus {
    /// Session accepted and active; EV is (or can be) charging.
    Active,
    /// Session finished. No further updates will be sent.
    Completed,
    /// Session declared invalid; will not be billed.
    Invalid,
    /// Session pending; not all pre-conditions met yet.
    Pending,
    /// Session started by a reservation; actual charging has not begun.
    Reservation,
}

// ── ProfileType ───────────────────────────────────────────────────────────────

/// Smart-charging profile preference set by the EV driver.
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — ProfileType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ProfileType {
    /// Driver prefers the cheapest available charging profile.
    Cheap,
    /// Driver wants maximum charging speed; willing to pay a premium.
    Fast,
    /// Driver prefers the greenest (most renewable) energy.
    Green,
    /// Driver has no special preferences.
    Regular,
}

// ── ChargingPreferencesResponse ───────────────────────────────────────────────

/// Response to a `PUT /sessions/{id}/charging_preferences` request.
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — ChargingPreferencesResponse enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ChargingPreferencesResponse {
    /// Preferences accepted; EVSE will try to fulfil them.
    Accepted,
    /// CPO requires `departure_time` to apply smart charging.
    DepartureRequired,
    /// CPO requires `energy_need` to apply smart charging.
    EnergyNeedRequired,
    /// The EVSE cannot fulfil the requested preferences.
    NotPossible,
    /// The requested `profile_type` is not supported by the EVSE.
    ProfileTypeNotSupported,
}

// ── ChargingPreferences ───────────────────────────────────────────────────────

/// Driver charging preferences sent to the CPO during an active session.
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — ChargingPreferences object.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChargingPreferences {
    /// Desired smart-charging profile.
    pub profile_type: ProfileType,
    /// Expected departure time (driver estimate; not a guarantee).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub departure_time: Option<DateTime<Utc>>,
    /// Requested energy in kWh to charge before `departure_time`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub energy_need: Option<f64>,
    /// Whether the driver allows vehicle-to-grid (V2G) discharging.
    /// Defaults to `false` when absent.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub discharge_allowed: Option<bool>,
}

// ── Session ───────────────────────────────────────────────────────────────────

/// A charging session object owned by the CPO.
///
/// Describes one charging session from start to finish, including token,
/// location references, energy consumed, and cost. Transmitted from CPO
/// to eMSP via push (PUT/PATCH) or pull (GET list).
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — Session object.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Session {
    /// ISO 3166-1 alpha-2 country code of the CPO that owns this session.
    pub country_code: CiString2,
    /// Party ID of the CPO that owns this session.
    pub party_id: CiString3,
    /// Unique session ID within the CPO's platform.
    pub id: CiString36,
    /// Timestamp when the session became ACTIVE (or was created if PENDING).
    pub start_date_time: DateTime<Utc>,
    /// Timestamp when the session ended. `None` if still active.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub end_date_time: Option<DateTime<Utc>>,
    /// Total energy charged so far, in kWh.
    pub kwh: f64,
    /// Token used to start the session.
    pub cdr_token: CdrToken,
    /// Authentication method used (may change during the session).
    pub auth_method: AuthMethod,
    /// Authorization reference from the eMSP (e.g. from StartSession).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub authorization_reference: Option<CiString36>,
    /// `Location.id` of the CPO location where this session is happening.
    pub location_id: CiString36,
    /// `EVSE.uid` at the location (`#NA` for reservation without EVSE assignment).
    pub evse_uid: CiString36,
    /// `Connector.id` at the EVSE (`#NA` for reservation without connector assignment).
    pub connector_id: CiString36,
    /// Optional meter identifier inside the charge point.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub meter_id: Option<String>,
    /// ISO 4217 currency code (e.g. `"EUR"`).
    pub currency: String,
    /// Charging periods recorded so far (may be empty if no periods yet).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub charging_periods: Vec<ChargingPeriod>,
    /// Total cost of the session so far in `currency`. `None` if not yet known.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub total_cost: Option<Price>,
    /// Current status of the session.
    pub status: SessionStatus,
    /// Timestamp of the last update (or creation) of this session object.
    pub last_updated: DateTime<Utc>,
}

// ── ConnectorType ─────────────────────────────────────────────────────────────

/// Standard of an EVSE connector socket or plug.
///
/// Forward reference: mirrors the Locations module's `ConnectorType`. Defined
/// here so that `CdrLocation` compiles while PR #31 (Locations types) is still
/// pending human review.
///
/// Spec: `specs/ocpi/2.2.1/mod_locations.asciidoc` — ConnectorType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ConnectorType {
    /// CHAdeMO, DC.
    Chademo,
    /// ChaoJi — next-gen connector harmonized between CHAdeMO and GB/T. DC.
    Chaoji,
    /// Domestic household type A — NEMA 1-15, 2 pins.
    DomesticA,
    /// Domestic household type B — NEMA 5-15, 3 pins.
    DomesticB,
    /// Domestic household type C — CEE 7/17, 2 pins.
    DomesticC,
    /// Domestic household type D — 3 pin.
    DomesticD,
    /// Domestic household type E — CEE 7/5, 3 pins.
    DomesticE,
    /// Domestic household type F — CEE 7/4 Schuko, 3 pins.
    DomesticF,
    /// Domestic household type G — BS 1363, Commonwealth, 3 pins.
    DomesticG,
    /// Domestic household type H — SI-32, 3 pins.
    DomesticH,
    /// Domestic household type I — AS 3112, 3 pins.
    DomesticI,
    /// Domestic household type J — SEV 1011, 3 pins.
    DomesticJ,
    /// Domestic household type K — DS 60884-2-D1, 3 pins.
    DomesticK,
    /// Domestic household type L — CEI 23-16-VII, 3 pins.
    DomesticL,
    /// Domestic household type M — BS 546, 3 pins.
    DomesticM,
    /// Domestic household type N — NBR 14136, 3 pins.
    DomesticN,
    /// Domestic household type O — TIS 166-2549, 3 pins.
    DomesticO,
    /// Guobiao GB/T 20234.2 AC socket/connector.
    GbtAc,
    /// Guobiao GB/T 20234.3 DC connector.
    GbtDc,
    /// IEC 60309-2 Industrial single phase 16 A (typically blue).
    #[serde(rename = "IEC_60309_2_single_16")]
    Iec6030921Single16,
    /// IEC 60309-2 Industrial three phase 16 A (typically red).
    #[serde(rename = "IEC_60309_2_three_16")]
    Iec6030922Three16,
    /// IEC 60309-2 Industrial three phase 32 A (typically red).
    #[serde(rename = "IEC_60309_2_three_32")]
    Iec6030922Three32,
    /// IEC 60309-2 Industrial three phase 64 A (typically red).
    #[serde(rename = "IEC_60309_2_three_64")]
    Iec6030922Three64,
    /// IEC 62196 Type 1 "SAE J1772".
    #[serde(rename = "IEC_62196_T1")]
    Iec62196T1,
    /// Combo Type 1 based, DC.
    #[serde(rename = "IEC_62196_T1_COMBO")]
    Iec62196T1Combo,
    /// IEC 62196 Type 2 "Mennekes".
    #[serde(rename = "IEC_62196_T2")]
    Iec62196T2,
    /// Combo Type 2 based, DC.
    #[serde(rename = "IEC_62196_T2_COMBO")]
    Iec62196T2Combo,
    /// IEC 62196 Type 3A.
    #[serde(rename = "IEC_62196_T3A")]
    Iec62196T3a,
    /// IEC 62196 Type 3C "Scame".
    #[serde(rename = "IEC_62196_T3C")]
    Iec62196T3c,
    /// NEMA 5-20, 3 pins.
    #[serde(rename = "NEMA_5_20")]
    Nema520,
    /// NEMA 6-30, 3 pins.
    #[serde(rename = "NEMA_6_30")]
    Nema630,
    /// NEMA 6-50, 3 pins.
    #[serde(rename = "NEMA_6_50")]
    Nema650,
    /// NEMA 10-30, 3 pins.
    #[serde(rename = "NEMA_10_30")]
    Nema1030,
    /// NEMA 10-50, 3 pins.
    #[serde(rename = "NEMA_10_50")]
    Nema1050,
    /// NEMA 14-30, 3 pins, 30 A.
    #[serde(rename = "NEMA_14_30")]
    Nema1430,
    /// NEMA 14-50, 3 pins, 50 A.
    #[serde(rename = "NEMA_14_50")]
    Nema1450,
    /// On-board bottom-up pantograph (typically for bus charging).
    PantographBottomUp,
    /// Off-board top-down pantograph (typically for bus charging).
    PantographTopDown,
    /// Tesla Connector "Roadster"-type (round, 4 pin).
    TeslaR,
    /// Tesla Connector "Model S"-type (oval, 5 pin).
    TeslaS,
}

// ── ConnectorFormat ───────────────────────────────────────────────────────────

/// Whether the connector is a socket (user brings cable) or an attached cable.
///
/// Forward reference: mirrors the Locations module's `ConnectorFormat`.
///
/// Spec: `specs/ocpi/2.2.1/mod_locations.asciidoc` — ConnectorFormat enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ConnectorFormat {
    /// The connector is a socket; the EV user needs to bring a fitting plug.
    Socket,
    /// The connector is an attached cable; the EV needs a fitting inlet.
    Cable,
}

// ── PowerType ─────────────────────────────────────────────────────────────────

/// Electrical power type at an EVSE.
///
/// Forward reference: mirrors the Locations module's `PowerType`.
///
/// Spec: `specs/ocpi/2.2.1/mod_locations.asciidoc` — PowerType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PowerType {
    /// AC single phase.
    #[serde(rename = "AC_1_PHASE")]
    Ac1Phase,
    /// AC two phases (two of three available phases connected).
    #[serde(rename = "AC_2_PHASE")]
    Ac2Phase,
    /// AC two phases using a split-phase system.
    #[serde(rename = "AC_2_PHASE_SPLIT")]
    Ac2PhaseSplit,
    /// AC three phases.
    #[serde(rename = "AC_3_PHASE")]
    Ac3Phase,
    /// Direct current.
    #[serde(rename = "DC")]
    Dc,
}

// ── CdrLocation ───────────────────────────────────────────────────────────────

/// Compact location snapshot embedded in a CDR.
///
/// Contains only the fields from the full `Location` object that are relevant
/// to a concluded charging session: the specific EVSE and connector used.
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — CdrLocation class.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CdrLocation {
    /// Unique location ID within the CPO's platform.
    pub id: CiString36,
    /// Human-readable display name of the location.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    /// Street/block name and house number.
    pub address: String,
    /// City or town.
    pub city: String,
    /// Postal code (may be absent at highway locations in some countries).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub postal_code: Option<String>,
    /// State or province (only when relevant).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub state: Option<String>,
    /// ISO 3166-1 alpha-3 country code.
    pub country: String,
    /// GPS coordinates of the location.
    pub coordinates: GeoLocation,
    /// Technical EVSE identifier within the CPO's platform.
    pub evse_uid: CiString36,
    /// eMI3-compliant human-readable EVSE ID (up to 48 chars).
    pub evse_id: CiString48,
    /// Connector identifier within the EVSE.
    pub connector_id: CiString36,
    /// Physical connector standard.
    pub connector_standard: ConnectorType,
    /// Connector format (socket or attached cable).
    pub connector_format: ConnectorFormat,
    /// Electrical power type.
    pub connector_power_type: PowerType,
}

// ── SignedValue ───────────────────────────────────────────────────────────────

/// One signed meter value within a `SignedData` block.
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — SignedValue class.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SignedValue {
    /// Nature of the value (e.g. `"Start"`, `"End"`, `"Intermediate"`).
    pub nature: CiString<32>,
    /// Plain (un-encoded) meter data string.
    pub plain_data: String,
    /// Base64-encoded signed meter data blob.
    pub signed_data: String,
}

// ── SignedData ────────────────────────────────────────────────────────────────

/// Signed metering data attached to a CDR (e.g. for German Eichrecht).
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — SignedData class.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SignedData {
    /// Name of the encoding method (assigned by a standards body or vendor).
    pub encoding_method: CiString36,
    /// Version of the encoding method, when applicable.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub encoding_method_version: Option<i32>,
    /// Base64-encoded public key used to sign the data.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub public_key: Option<String>,
    /// One or more signed meter values.
    pub signed_values: Vec<SignedValue>,
    /// URL where the EV driver can verify the signed data.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub url: Option<String>,
}

// ── Tariffs module ────────────────────────────────────────────────────────────
//
// Spec: specs/ocpi/2.2.1/mod_tariffs.asciidoc — §Object description + §Data types

/// The optional tariff type, used to distinguish tariffs for specific use-cases.
///
/// Spec: `specs/ocpi/2.2.1/mod_tariffs.asciidoc` — TariffType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TariffType {
    /// Used to describe that a tariff is valid when ad-hoc payment is used at the charge point.
    AdHocPayment,
    /// Used to describe that a tariff is valid when Charging Preference: CHEAP is set for the session.
    ProfileCheap,
    /// Used to describe that a tariff is valid when Charging Preference: FAST is set for the session.
    ProfileFast,
    /// Used to describe that a tariff is valid when Charging Preference: GREEN is set for the session.
    ProfileGreen,
    /// Used to describe that a tariff is valid for a regular charging session.
    Regular,
}

/// Dimension used for a price component.
///
/// Spec: `specs/ocpi/2.2.1/mod_tariffs.asciidoc` — TariffDimensionType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TariffDimensionType {
    /// Defined in kWh, step_size multiplier: 1 Wh.
    Energy,
    /// Flat fee, no unit.
    Flat,
    /// Time not charging: defined in hours, step_size multiplier: 1 second.
    ParkingTime,
    /// Time charging: defined in hours, step_size multiplier: 1 second.
    Time,
}

/// Day of week for tariff restrictions.
///
/// Spec: `specs/ocpi/2.2.1/mod_tariffs.asciidoc` — DayOfWeek enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DayOfWeek {
    /// Monday.
    Monday,
    /// Tuesday.
    Tuesday,
    /// Wednesday.
    Wednesday,
    /// Thursday.
    Thursday,
    /// Friday.
    Friday,
    /// Saturday.
    Saturday,
    /// Sunday.
    Sunday,
}

/// Type of restriction applicable to a reservation.
///
/// Spec: `specs/ocpi/2.2.1/mod_tariffs.asciidoc` — ReservationRestrictionType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ReservationRestrictionType {
    /// Used in TariffElements to define the price of a reservation.
    Reservation,
    /// Used in TariffElements to define the price of a reservation that expires (i.e. driver does not start charging).
    ReservationExpires,
}

/// Restrictions that limit when a `TariffElement` applies.
///
/// All fields are optional. When a field is `None` the corresponding dimension
/// is unrestricted. Ranges are inclusive on both ends.
///
/// Spec: `specs/ocpi/2.2.1/mod_tariffs.asciidoc` — TariffRestrictions class.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct TariffRestrictions {
    /// Start time of day in local time, applies every day, format: `HH:MM` (24h).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub start_time: Option<String>,
    /// End time of day in local time, applies every day, format: `HH:MM` (24h).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub end_time: Option<String>,
    /// Start date, applies from this day (inclusive), format: `YYYY-MM-DD`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub start_date: Option<String>,
    /// End date, applies until this day (inclusive), format: `YYYY-MM-DD`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub end_date: Option<String>,
    /// Minimum consumed energy (kWh) — inclusive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub min_kwh: Option<f64>,
    /// Maximum consumed energy (kWh) — exclusive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_kwh: Option<f64>,
    /// Minimum current (A) over the entire charging session — inclusive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub min_current: Option<f64>,
    /// Maximum current (A) over the entire charging session — exclusive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_current: Option<f64>,
    /// Minimum power (kW) over the entire charging session — inclusive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub min_power: Option<f64>,
    /// Maximum power (kW) over the entire charging session — exclusive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_power: Option<f64>,
    /// Minimum duration (seconds) of the charging session — inclusive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub min_duration: Option<u32>,
    /// Maximum duration (seconds) of the charging session — exclusive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_duration: Option<u32>,
    /// Applicable days of the week.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub day_of_week: Vec<DayOfWeek>,
    /// Restriction on charging or parking reservation.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reservation: Option<ReservationRestrictionType>,
}

/// A single dimension component of a tariff element.
///
/// Spec: `specs/ocpi/2.2.1/mod_tariffs.asciidoc` — PriceComponent class.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PriceComponent {
    /// The dimension that this component applies to.
    ///
    /// Field renamed from spec `type` (Rust keyword).
    #[serde(rename = "type")]
    pub component_type: TariffDimensionType,
    /// Price per unit (excl. VAT) for this component.
    pub price: f64,
    /// Applicable VAT percentage for this tariff dimension. If omitted, no VAT applies.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub vat: Option<f64>,
    /// Minimum amount to be billed. Unit depends on the `component_type`.
    pub step_size: u32,
}

/// A set of price components that apply under an optional set of restrictions.
///
/// Spec: `specs/ocpi/2.2.1/mod_tariffs.asciidoc` — TariffElement class.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TariffElement {
    /// List of price components that make up the pricing of this tariff.
    pub price_components: Vec<PriceComponent>,
    /// Optional restrictions that this element may not be used with.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub restrictions: Option<TariffRestrictions>,
}

/// An OCPI Tariff object. Describes a pricing scheme for EV charging sessions.
///
/// Spec: `specs/ocpi/2.2.1/mod_tariffs.asciidoc` — Tariff object.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tariff {
    /// ISO 3166-1 alpha-2 country code of the CPO that owns this tariff.
    pub country_code: CiString2,
    /// Party ID of the CPO that owns this tariff.
    pub party_id: CiString3,
    /// Unique tariff ID within the CPO's platform.
    pub id: CiString36,
    /// ISO 4217 currency code.
    pub currency: String,
    /// The optional tariff type. When absent this tariff can be used for all sessions.
    ///
    /// Field renamed from spec `type` (Rust keyword).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none", default)]
    pub tariff_type: Option<TariffType>,
    /// Human-readable name(s) or description(s) in various languages.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tariff_alt_text: Vec<DisplayText>,
    /// Alternative URL to a tariff information web page.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tariff_alt_url: Option<Url>,
    /// Minimum charging price (excl. VAT). When set, the sum of the billed price components
    /// will never be lower than this price.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub min_price: Option<Price>,
    /// Maximum charging price (excl. VAT). When set, the sum of the billed price components
    /// will never exceed this price.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_price: Option<Price>,
    /// List of tariff elements.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub elements: Vec<TariffElement>,
    /// When this tariff becomes active.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub start_date_time: Option<DateTime<Utc>>,
    /// When this tariff becomes inactive.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub end_date_time: Option<DateTime<Utc>>,
    /// Details on the energy supplied with this tariff.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub energy_mix: Option<EnergyMix>,
    /// Timestamp of the last update (or creation) of this tariff.
    pub last_updated: DateTime<Utc>,
}

// ── Cdr ───────────────────────────────────────────────────────────────────────

/// A Charge Detail Record — the billing artifact for a completed charging session.
///
/// CDRs are immutable after creation. Corrections are issued via a Credit CDR
/// (set `credit = true` and point `credit_reference_id` at the original CDR).
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — CDR object.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Cdr {
    /// ISO 3166-1 alpha-2 country code of the CPO that owns this CDR.
    pub country_code: CiString2,
    /// Party ID of the CPO that owns this CDR.
    pub party_id: CiString3,
    /// Unique CDR ID. Credit CDRs may append a suffix (e.g. `-C`), raising
    /// the limit to 39 chars; normal CDRs must stay within 36.
    pub id: CiString39,
    /// Timestamp when charging started (or reservation started).
    pub start_date_time: DateTime<Utc>,
    /// Timestamp when the session ended (charging + any post-charge parking).
    pub end_date_time: DateTime<Utc>,
    /// ID of the corresponding `Session`, if the Sessions module is in use.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub session_id: Option<CiString36>,
    /// Token used to start the session.
    pub cdr_token: CdrToken,
    /// Authentication method used (the last method if multiple were used).
    pub auth_method: AuthMethod,
    /// Authorization reference provided by the eMSP, when applicable.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub authorization_reference: Option<CiString36>,
    /// Compact location snapshot for the EVSE and connector used.
    pub cdr_location: CdrLocation,
    /// Meter identifier inside the charge point, if known.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub meter_id: Option<String>,
    /// ISO 4217 currency code for all cost fields.
    pub currency: String,
    /// Tariffs applicable to this session (may be empty).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tariffs: Vec<Tariff>,
    /// Charging periods that make up this session (one or more required).
    pub charging_periods: Vec<ChargingPeriod>,
    /// Signed metering data (e.g. Eichrecht), when present.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub signed_data: Option<SignedData>,
    /// Total cost of the transaction in `currency`.
    pub total_cost: Price,
    /// Fixed cost component (start fee, etc.), excluding parking/reservation fixed fees.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub total_fixed_cost: Option<Price>,
    /// Total energy charged, in kWh.
    pub total_energy: f64,
    /// Cost of all energy consumed.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub total_energy_cost: Option<Price>,
    /// Total session duration (charging + non-charging), in hours.
    pub total_time: f64,
    /// Cost of charging-time duration.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub total_time_cost: Option<Price>,
    /// Time the EV was connected but not charging, in hours.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub total_parking_time: Option<f64>,
    /// Cost of post-charge parking.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub total_parking_cost: Option<Price>,
    /// Cost of the reservation, if any.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub total_reservation_cost: Option<Price>,
    /// Human-readable remark (e.g. reason for early stop).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub remark: Option<String>,
    /// Invoice reference — links this CDR to a future invoice.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub invoice_reference_id: Option<CiString39>,
    /// `true` if this CDR is a Credit CDR that negates a previous session.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub credit: Option<bool>,
    /// ID of the original CDR being credited (required when `credit` is `true`).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub credit_reference_id: Option<CiString39>,
    /// `true` if this session used the driver's home charger and energy cost
    /// compensation applies.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub home_charging_compensation: Option<bool>,
    /// Timestamp of the last update (or creation) of this CDR object.
    pub last_updated: DateTime<Utc>,
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::common::BusinessDetails;

    fn make_role(role: Role, party: &str, country: &str) -> CredentialsRole {
        CredentialsRole {
            role,
            business_details: BusinessDetails {
                name: "Test Party".into(),
                website: None,
                logo: None,
            },
            party_id: CiString3::try_from(party).unwrap(),
            country_code: CiString2::try_from(country).unwrap(),
        }
    }

    fn cpo_credentials() -> Credentials {
        Credentials {
            token: "TOKEN_B".into(),
            url: Url::try_from("https://example.com/ocpi/versions").unwrap(),
            roles: vec![make_role(Role::Cpo, "EXA", "NL")],
        }
    }

    // ── Serde round-trips ─────────────────────────────────────────────────────

    #[test]
    fn credentials_serde_roundtrip() {
        let c = cpo_credentials();
        let json = serde_json::to_string(&c).unwrap();
        let back: Credentials = serde_json::from_str(&json).unwrap();
        assert_eq!(back, c);
    }

    #[test]
    fn credentials_role_serde_roundtrip() {
        let r = make_role(Role::Emsp, "MSP", "DE");
        let json = serde_json::to_string(&r).unwrap();
        let back: CredentialsRole = serde_json::from_str(&json).unwrap();
        assert_eq!(back, r);
    }

    /// Spec example: minimal CPO credentials object.
    #[test]
    fn credentials_spec_example_minimal_cpo() {
        let json = r#"{
            "token": "ZXhhbXBsZS10b2tlbgo=",
            "url": "https://example.com/ocpi/versions",
            "roles": [
                {
                    "role": "CPO",
                    "business_details": {"name": "Example CPO"},
                    "party_id": "EXA",
                    "country_code": "NL"
                }
            ]
        }"#;
        let c: Credentials = serde_json::from_str(json).unwrap();
        assert_eq!(c.token, "ZXhhbXBsZS10b2tlbgo=");
        assert_eq!(c.roles.len(), 1);
        assert_eq!(c.roles[0].role, Role::Cpo);
        assert_eq!(c.roles[0].party_id.as_str(), "EXA");
        assert_eq!(c.roles[0].country_code.as_str(), "NL");
        assert_eq!(c.roles[0].business_details.name, "Example CPO");
    }

    /// Spec example: combined CPO + eMSP credentials (multi-role, schema-legal).
    #[test]
    fn credentials_spec_example_multi_role() {
        let json = r#"{
            "token": "TOKEN_C",
            "url": "https://example.com/ocpi/versions",
            "roles": [
                {
                    "role": "CPO",
                    "business_details": {"name": "Example Operator"},
                    "party_id": "EXA",
                    "country_code": "NL"
                },
                {
                    "role": "EMSP",
                    "business_details": {"name": "Example Provider"},
                    "party_id": "EXB",
                    "country_code": "NL"
                }
            ]
        }"#;
        let c: Credentials = serde_json::from_str(json).unwrap();
        assert_eq!(c.roles.len(), 2);
        assert_eq!(c.roles[0].role, Role::Cpo);
        assert_eq!(c.roles[1].role, Role::Emsp);
    }

    // ── Validation ────────────────────────────────────────────────────────────

    #[test]
    fn validate_rejects_empty_roles() {
        let c = Credentials {
            token: "T".into(),
            url: Url::try_from("https://example.com/ocpi/versions").unwrap(),
            roles: vec![],
        };
        assert!(c.validate().is_err());
    }

    #[test]
    fn validate_accepts_single_role() {
        assert!(cpo_credentials().validate().is_ok());
    }

    #[test]
    fn check_single_role_rejects_multi_role() {
        let json = r#"{
            "token": "T",
            "url": "https://example.com/ocpi/versions",
            "roles": [
                {"role":"CPO","business_details":{"name":"A"},"party_id":"AAA","country_code":"NL"},
                {"role":"EMSP","business_details":{"name":"B"},"party_id":"BBB","country_code":"NL"}
            ]
        }"#;
        let c: Credentials = serde_json::from_str(json).unwrap();
        assert!(c.check_single_role().is_err());
    }

    #[test]
    fn check_single_role_accepts_single() {
        assert!(cpo_credentials().check_single_role().is_ok());
    }

    // ── TokenType ─────────────────────────────────────────────────────────────

    #[test]
    fn token_type_serde_screaming_snake() {
        assert_eq!(
            serde_json::to_string(&TokenType::AdHocUser).unwrap(),
            "\"AD_HOC_USER\""
        );
        assert_eq!(
            serde_json::to_string(&TokenType::AppUser).unwrap(),
            "\"APP_USER\""
        );
        assert_eq!(serde_json::to_string(&TokenType::Rfid).unwrap(), "\"RFID\"");
        assert_eq!(
            serde_json::to_string(&TokenType::Other).unwrap(),
            "\"OTHER\""
        );
    }

    #[test]
    fn token_type_roundtrip() {
        for tt in [
            TokenType::AdHocUser,
            TokenType::AppUser,
            TokenType::Other,
            TokenType::Rfid,
        ] {
            let json = serde_json::to_string(&tt).unwrap();
            let back: TokenType = serde_json::from_str(&json).unwrap();
            assert_eq!(back, tt);
        }
    }

    // ── AuthMethod ────────────────────────────────────────────────────────────

    #[test]
    fn auth_method_serde_screaming_snake() {
        assert_eq!(
            serde_json::to_string(&AuthMethod::AuthRequest).unwrap(),
            "\"AUTH_REQUEST\""
        );
        assert_eq!(
            serde_json::to_string(&AuthMethod::Command).unwrap(),
            "\"COMMAND\""
        );
        assert_eq!(
            serde_json::to_string(&AuthMethod::Whitelist).unwrap(),
            "\"WHITELIST\""
        );
    }

    #[test]
    fn auth_method_roundtrip() {
        for am in [
            AuthMethod::AuthRequest,
            AuthMethod::Command,
            AuthMethod::Whitelist,
        ] {
            let json = serde_json::to_string(&am).unwrap();
            let back: AuthMethod = serde_json::from_str(&json).unwrap();
            assert_eq!(back, am);
        }
    }

    // ── CdrToken ──────────────────────────────────────────────────────────────

    fn make_cdr_token() -> CdrToken {
        CdrToken {
            country_code: CiString2::try_from("NL").unwrap(),
            party_id: CiString3::try_from("TNM").unwrap(),
            uid: CiString36::try_from("012345678").unwrap(),
            token_type: TokenType::Rfid,
            contract_id: CiString36::try_from("NL8ACC12E46L89").unwrap(),
        }
    }

    #[test]
    fn cdr_token_serde_roundtrip() {
        let t = make_cdr_token();
        let json = serde_json::to_string(&t).unwrap();
        // field must be named "type" on the wire
        assert!(json.contains("\"type\""));
        let back: CdrToken = serde_json::from_str(&json).unwrap();
        assert_eq!(back, t);
    }

    #[test]
    fn cdr_token_deserialize_from_spec_example() {
        let json = r#"{
            "country_code": "NL",
            "party_id": "TNM",
            "uid": "012345678",
            "type": "RFID",
            "contract_id": "NL8ACC12E46L89"
        }"#;
        let t: CdrToken = serde_json::from_str(json).unwrap();
        assert_eq!(t.token_type, TokenType::Rfid);
        assert_eq!(t.uid.as_str(), "012345678");
    }

    // ── CdrDimensionType / CdrDimension ───────────────────────────────────────

    #[test]
    fn cdr_dimension_type_serde() {
        assert_eq!(
            serde_json::to_string(&CdrDimensionType::Energy).unwrap(),
            "\"ENERGY\""
        );
        assert_eq!(
            serde_json::to_string(&CdrDimensionType::StateOfCharge).unwrap(),
            "\"STATE_OF_CHARGE\""
        );
        assert_eq!(
            serde_json::to_string(&CdrDimensionType::ParkingTime).unwrap(),
            "\"PARKING_TIME\""
        );
    }

    #[test]
    fn cdr_dimension_serde_roundtrip() {
        let d = CdrDimension {
            dimension_type: CdrDimensionType::Energy,
            volume: 15.342,
        };
        let json = serde_json::to_string(&d).unwrap();
        assert!(json.contains("\"type\""));
        let back: CdrDimension = serde_json::from_str(&json).unwrap();
        assert!((back.volume - 15.342).abs() < f64::EPSILON);
        assert_eq!(back.dimension_type, CdrDimensionType::Energy);
    }

    // ── ChargingPeriod ────────────────────────────────────────────────────────

    #[test]
    fn charging_period_serde_roundtrip() {
        let p = ChargingPeriod {
            start_date_time: chrono::DateTime::parse_from_rfc3339("2015-06-29T22:39:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
            dimensions: vec![CdrDimension {
                dimension_type: CdrDimensionType::Energy,
                volume: 0.0,
            }],
            tariff_id: None,
        };
        let json = serde_json::to_string(&p).unwrap();
        assert!(!json.contains("tariff_id"));
        let back: ChargingPeriod = serde_json::from_str(&json).unwrap();
        assert_eq!(back, p);
    }

    #[test]
    fn charging_period_with_tariff_id_roundtrip() {
        let p = ChargingPeriod {
            start_date_time: chrono::DateTime::parse_from_rfc3339("2015-06-29T22:39:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
            dimensions: vec![CdrDimension {
                dimension_type: CdrDimensionType::Time,
                volume: 1.5,
            }],
            tariff_id: Some(CiString36::try_from("12").unwrap()),
        };
        let json = serde_json::to_string(&p).unwrap();
        assert!(json.contains("\"tariff_id\""));
        let back: ChargingPeriod = serde_json::from_str(&json).unwrap();
        assert_eq!(back, p);
    }

    // ── SessionStatus / ProfileType / ChargingPreferencesResponse ─────────────

    #[test]
    fn session_status_serde() {
        assert_eq!(
            serde_json::to_string(&SessionStatus::Active).unwrap(),
            "\"ACTIVE\""
        );
        assert_eq!(
            serde_json::to_string(&SessionStatus::Completed).unwrap(),
            "\"COMPLETED\""
        );
        assert_eq!(
            serde_json::to_string(&SessionStatus::Reservation).unwrap(),
            "\"RESERVATION\""
        );
    }

    #[test]
    fn profile_type_serde() {
        assert_eq!(
            serde_json::to_string(&ProfileType::Cheap).unwrap(),
            "\"CHEAP\""
        );
        assert_eq!(
            serde_json::to_string(&ProfileType::Fast).unwrap(),
            "\"FAST\""
        );
        assert_eq!(
            serde_json::to_string(&ProfileType::Green).unwrap(),
            "\"GREEN\""
        );
        assert_eq!(
            serde_json::to_string(&ProfileType::Regular).unwrap(),
            "\"REGULAR\""
        );
    }

    #[test]
    fn charging_preferences_response_serde() {
        assert_eq!(
            serde_json::to_string(&ChargingPreferencesResponse::ProfileTypeNotSupported).unwrap(),
            "\"PROFILE_TYPE_NOT_SUPPORTED\""
        );
        assert_eq!(
            serde_json::to_string(&ChargingPreferencesResponse::DepartureRequired).unwrap(),
            "\"DEPARTURE_REQUIRED\""
        );
    }

    // ── ChargingPreferences ───────────────────────────────────────────────────

    #[test]
    fn charging_preferences_serde_roundtrip() {
        let p = ChargingPreferences {
            profile_type: ProfileType::Green,
            departure_time: None,
            energy_need: Some(40.0),
            discharge_allowed: Some(false),
        };
        let json = serde_json::to_string(&p).unwrap();
        assert!(!json.contains("departure_time"));
        let back: ChargingPreferences = serde_json::from_str(&json).unwrap();
        assert_eq!(back, p);
    }

    #[test]
    fn charging_preferences_minimal_roundtrip() {
        let json = r#"{"profile_type":"CHEAP"}"#;
        let p: ChargingPreferences = serde_json::from_str(json).unwrap();
        assert_eq!(p.profile_type, ProfileType::Cheap);
        assert!(p.departure_time.is_none());
        assert!(p.energy_need.is_none());
        assert!(p.discharge_allowed.is_none());
    }

    // ── Session ───────────────────────────────────────────────────────────────

    fn make_session() -> Session {
        Session {
            country_code: CiString2::try_from("NL").unwrap(),
            party_id: CiString3::try_from("TNM").unwrap(),
            id: CiString36::try_from("101").unwrap(),
            start_date_time: chrono::DateTime::parse_from_rfc3339("2020-03-09T10:17:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
            end_date_time: None,
            kwh: 0.0,
            cdr_token: make_cdr_token(),
            auth_method: AuthMethod::Whitelist,
            authorization_reference: None,
            location_id: CiString36::try_from("LOC1").unwrap(),
            evse_uid: CiString36::try_from("3256").unwrap(),
            connector_id: CiString36::try_from("1").unwrap(),
            meter_id: None,
            currency: "EUR".into(),
            charging_periods: vec![],
            total_cost: None,
            status: SessionStatus::Pending,
            last_updated: chrono::DateTime::parse_from_rfc3339("2020-03-09T10:17:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
        }
    }

    #[test]
    fn session_serde_roundtrip() {
        let s = make_session();
        let json = serde_json::to_string(&s).unwrap();
        let back: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(back, s);
    }

    #[test]
    fn session_optional_fields_absent_when_none() {
        let s = make_session();
        let json = serde_json::to_string(&s).unwrap();
        assert!(!json.contains("end_date_time"));
        assert!(!json.contains("authorization_reference"));
        assert!(!json.contains("meter_id"));
        assert!(!json.contains("charging_periods"));
        assert!(!json.contains("total_cost"));
    }

    #[test]
    fn session_deserialize_spec_example_simple_start() {
        // Based on the spec's "simple start" example (§Sessions module §Examples)
        let json = r#"{
            "country_code": "NL",
            "party_id": "TNM",
            "id": "101",
            "start_date_time": "2020-03-09T10:17:09Z",
            "kwh": 0.00,
            "cdr_token": {
                "country_code": "NL",
                "party_id": "TNM",
                "uid": "012345678",
                "type": "RFID",
                "contract_id": "NL8ACC12E46L89"
            },
            "auth_method": "WHITELIST",
            "location_id": "LOC1",
            "evse_uid": "3256",
            "connector_id": "1",
            "currency": "EUR",
            "status": "PENDING",
            "last_updated": "2020-03-09T10:17:09Z"
        }"#;
        let s: Session = serde_json::from_str(json).unwrap();
        assert_eq!(s.id.as_str(), "101");
        assert_eq!(s.status, SessionStatus::Pending);
        assert_eq!(s.auth_method, AuthMethod::Whitelist);
        assert_eq!(s.cdr_token.token_type, TokenType::Rfid);
        assert!(s.charging_periods.is_empty());
        assert!(s.total_cost.is_none());
    }

    #[test]
    fn session_deserialize_with_charging_period() {
        let json = r#"{
            "country_code": "NL",
            "party_id": "TNM",
            "id": "101",
            "start_date_time": "2020-03-09T10:17:09Z",
            "end_date_time": "2020-03-09T11:01:09Z",
            "kwh": 41.12,
            "cdr_token": {
                "country_code": "NL",
                "party_id": "TNM",
                "uid": "012345678",
                "type": "RFID",
                "contract_id": "NL8ACC12E46L89"
            },
            "auth_method": "WHITELIST",
            "location_id": "LOC1",
            "evse_uid": "3256",
            "connector_id": "1",
            "currency": "EUR",
            "charging_periods": [
                {
                    "start_date_time": "2020-03-09T10:17:09Z",
                    "dimensions": [
                        {"type": "ENERGY", "volume": 41.12}
                    ]
                }
            ],
            "total_cost": {"excl_vat": 8.50, "incl_vat": 9.35},
            "status": "COMPLETED",
            "last_updated": "2020-03-09T11:01:09Z"
        }"#;
        let s: Session = serde_json::from_str(json).unwrap();
        assert_eq!(s.status, SessionStatus::Completed);
        assert_eq!(s.charging_periods.len(), 1);
        assert_eq!(
            s.charging_periods[0].dimensions[0].dimension_type,
            CdrDimensionType::Energy
        );
        assert!(s.total_cost.is_some());
        assert!((s.kwh - 41.12).abs() < f64::EPSILON);
        assert!(s.end_date_time.is_some());
    }

    // ── ConnectorType / ConnectorFormat / PowerType ───────────────────────────

    #[test]
    fn connector_type_screaming_snake_standard_variants() {
        assert_eq!(
            serde_json::to_string(&ConnectorType::Chademo).unwrap(),
            "\"CHADEMO\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::DomesticA).unwrap(),
            "\"DOMESTIC_A\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::GbtAc).unwrap(),
            "\"GBT_AC\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::TeslaS).unwrap(),
            "\"TESLA_S\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::PantographBottomUp).unwrap(),
            "\"PANTOGRAPH_BOTTOM_UP\""
        );
    }

    #[test]
    fn connector_type_explicit_renames() {
        assert_eq!(
            serde_json::to_string(&ConnectorType::Iec6030921Single16).unwrap(),
            "\"IEC_60309_2_single_16\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::Iec6030922Three32).unwrap(),
            "\"IEC_60309_2_three_32\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::Iec62196T1).unwrap(),
            "\"IEC_62196_T1\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::Iec62196T2Combo).unwrap(),
            "\"IEC_62196_T2_COMBO\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::Iec62196T3a).unwrap(),
            "\"IEC_62196_T3A\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::Nema520).unwrap(),
            "\"NEMA_5_20\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorType::Nema1450).unwrap(),
            "\"NEMA_14_50\""
        );
    }

    #[test]
    fn connector_type_roundtrip() {
        for ct in [
            ConnectorType::Chademo,
            ConnectorType::Iec62196T2,
            ConnectorType::Iec6030921Single16,
            ConnectorType::Nema1030,
            ConnectorType::PantographTopDown,
        ] {
            let json = serde_json::to_string(&ct).unwrap();
            let back: ConnectorType = serde_json::from_str(&json).unwrap();
            assert_eq!(back, ct);
        }
    }

    #[test]
    fn connector_format_serde() {
        assert_eq!(
            serde_json::to_string(&ConnectorFormat::Socket).unwrap(),
            "\"SOCKET\""
        );
        assert_eq!(
            serde_json::to_string(&ConnectorFormat::Cable).unwrap(),
            "\"CABLE\""
        );
        let back: ConnectorFormat = serde_json::from_str("\"SOCKET\"").unwrap();
        assert_eq!(back, ConnectorFormat::Socket);
    }

    #[test]
    fn power_type_serde() {
        assert_eq!(
            serde_json::to_string(&PowerType::Ac1Phase).unwrap(),
            "\"AC_1_PHASE\""
        );
        assert_eq!(
            serde_json::to_string(&PowerType::Ac2PhaseSplit).unwrap(),
            "\"AC_2_PHASE_SPLIT\""
        );
        assert_eq!(serde_json::to_string(&PowerType::Dc).unwrap(), "\"DC\"");
        for pt in [
            PowerType::Ac1Phase,
            PowerType::Ac2Phase,
            PowerType::Ac2PhaseSplit,
            PowerType::Ac3Phase,
            PowerType::Dc,
        ] {
            let json = serde_json::to_string(&pt).unwrap();
            let back: PowerType = serde_json::from_str(&json).unwrap();
            assert_eq!(back, pt);
        }
    }

    // ── CdrLocation ───────────────────────────────────────────────────────────

    fn make_cdr_location() -> CdrLocation {
        CdrLocation {
            id: CiString36::try_from("LOC1").unwrap(),
            name: Some("Gent Zuid".into()),
            address: "F.Rooseveltlaan 3A".into(),
            city: "Gent".into(),
            postal_code: Some("9000".into()),
            state: None,
            country: "BEL".into(),
            coordinates: crate::common::GeoLocation {
                latitude: "51.047599".into(),
                longitude: "3.729944".into(),
            },
            evse_uid: CiString36::try_from("3256").unwrap(),
            evse_id: CiString48::try_from("BE*BEC*E041503001").unwrap(),
            connector_id: CiString36::try_from("1").unwrap(),
            connector_standard: ConnectorType::Iec62196T2,
            connector_format: ConnectorFormat::Socket,
            connector_power_type: PowerType::Ac3Phase,
        }
    }

    #[test]
    fn cdr_location_serde_roundtrip() {
        let loc = make_cdr_location();
        let json = serde_json::to_string(&loc).unwrap();
        assert!(json.contains("\"IEC_62196_T2\""));
        assert!(json.contains("\"SOCKET\""));
        assert!(json.contains("\"AC_3_PHASE\""));
        let back: CdrLocation = serde_json::from_str(&json).unwrap();
        assert_eq!(back, loc);
    }

    #[test]
    fn cdr_location_optional_fields_absent_when_none() {
        let mut loc = make_cdr_location();
        loc.name = None;
        loc.postal_code = None;
        let json = serde_json::to_string(&loc).unwrap();
        assert!(!json.contains("\"name\""));
        assert!(!json.contains("\"postal_code\""));
        assert!(!json.contains("\"state\""));
    }

    // ── SignedValue / SignedData ───────────────────────────────────────────────

    #[test]
    fn signed_value_serde_roundtrip() {
        let sv = SignedValue {
            nature: CiString::<32>::try_from("Start").unwrap(),
            plain_data: "1234567890".into(),
            signed_data: "SGVsbG8gV29ybGQ=".into(),
        };
        let json = serde_json::to_string(&sv).unwrap();
        assert!(json.contains("\"Start\""));
        let back: SignedValue = serde_json::from_str(&json).unwrap();
        assert_eq!(back, sv);
    }

    #[test]
    fn signed_data_serde_roundtrip() {
        let sd = SignedData {
            encoding_method: CiString36::try_from("OCMF").unwrap(),
            encoding_method_version: Some(1),
            public_key: Some("base64key==".into()),
            signed_values: vec![SignedValue {
                nature: CiString::<32>::try_from("End").unwrap(),
                plain_data: "data".into(),
                signed_data: "c2lnbg==".into(),
            }],
            url: Some("https://example.com/verify".into()),
        };
        let json = serde_json::to_string(&sd).unwrap();
        let back: SignedData = serde_json::from_str(&json).unwrap();
        assert_eq!(back, sd);
    }

    #[test]
    fn signed_data_optional_fields_absent_when_none() {
        let sd = SignedData {
            encoding_method: CiString36::try_from("OCMF").unwrap(),
            encoding_method_version: None,
            public_key: None,
            signed_values: vec![SignedValue {
                nature: CiString::<32>::try_from("Start").unwrap(),
                plain_data: "p".into(),
                signed_data: "s".into(),
            }],
            url: None,
        };
        let json = serde_json::to_string(&sd).unwrap();
        assert!(!json.contains("encoding_method_version"));
        assert!(!json.contains("public_key"));
        assert!(!json.contains("\"url\""));
    }

    // ── Cdr ───────────────────────────────────────────────────────────────────

    fn make_cdr() -> Cdr {
        Cdr {
            country_code: CiString2::try_from("NL").unwrap(),
            party_id: CiString3::try_from("TNM").unwrap(),
            id: CiString39::try_from("12345").unwrap(),
            start_date_time: chrono::DateTime::parse_from_rfc3339("2015-06-29T21:39:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
            end_date_time: chrono::DateTime::parse_from_rfc3339("2015-06-29T23:37:32Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
            session_id: None,
            cdr_token: make_cdr_token(),
            auth_method: AuthMethod::Whitelist,
            authorization_reference: None,
            cdr_location: make_cdr_location(),
            meter_id: None,
            currency: "EUR".into(),
            tariffs: vec![],
            charging_periods: vec![ChargingPeriod {
                start_date_time: chrono::DateTime::parse_from_rfc3339("2015-06-29T21:39:09Z")
                    .unwrap()
                    .with_timezone(&chrono::Utc),
                dimensions: vec![CdrDimension {
                    dimension_type: CdrDimensionType::Energy,
                    volume: 120.0,
                }],
                tariff_id: None,
            }],
            signed_data: None,
            total_cost: crate::common::Price {
                excl_vat: 4.00,
                incl_vat: None,
            },
            total_fixed_cost: None,
            total_energy: 120.0,
            total_energy_cost: None,
            total_time: 1.973,
            total_time_cost: None,
            total_parking_time: None,
            total_parking_cost: None,
            total_reservation_cost: None,
            remark: None,
            invoice_reference_id: None,
            credit: None,
            credit_reference_id: None,
            home_charging_compensation: None,
            last_updated: chrono::DateTime::parse_from_rfc3339("2015-06-29T23:37:32Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
        }
    }

    #[test]
    fn cdr_serde_roundtrip() {
        let cdr = make_cdr();
        let json = serde_json::to_string(&cdr).unwrap();
        let back: Cdr = serde_json::from_str(&json).unwrap();
        assert_eq!(back, cdr);
    }

    #[test]
    fn cdr_optional_fields_absent_when_none() {
        let cdr = make_cdr();
        let json = serde_json::to_string(&cdr).unwrap();
        assert!(!json.contains("session_id"));
        assert!(!json.contains("authorization_reference"));
        assert!(!json.contains("meter_id"));
        assert!(!json.contains("tariffs"));
        assert!(!json.contains("signed_data"));
        assert!(!json.contains("total_fixed_cost"));
        assert!(!json.contains("total_energy_cost"));
        assert!(!json.contains("total_time_cost"));
        assert!(!json.contains("total_parking_time"));
        assert!(!json.contains("total_parking_cost"));
        assert!(!json.contains("total_reservation_cost"));
        assert!(!json.contains("remark"));
        assert!(!json.contains("invoice_reference_id"));
        assert!(!json.contains("credit"));
        assert!(!json.contains("home_charging_compensation"));
    }

    #[test]
    fn cdr_credit_fields_present_when_set() {
        let mut cdr = make_cdr();
        cdr.credit = Some(true);
        cdr.credit_reference_id = Some(CiString39::try_from("12345").unwrap());
        let json = serde_json::to_string(&cdr).unwrap();
        assert!(json.contains("\"credit\":true"));
        assert!(json.contains("credit_reference_id"));
        let back: Cdr = serde_json::from_str(&json).unwrap();
        assert_eq!(back.credit, Some(true));
        assert_eq!(
            back.credit_reference_id.as_ref().map(|s| s.as_str()),
            Some("12345")
        );
    }

    #[test]
    fn cdr_spec_example_deserialization() {
        // Mirrors the structure from mod_cdrs.asciidoc §Example of a CDR.
        let json = r#"{
            "country_code": "NL",
            "party_id": "TNM",
            "id": "12345",
            "start_date_time": "2015-06-29T21:39:09Z",
            "end_date_time": "2015-06-29T23:37:32Z",
            "cdr_token": {
                "country_code": "NL",
                "party_id": "TNM",
                "uid": "012345678",
                "type": "RFID",
                "contract_id": "NL8ACC12E46L89"
            },
            "auth_method": "WHITELIST",
            "cdr_location": {
                "id": "LOC1",
                "address": "F.Rooseveltlaan 3A",
                "city": "Gent",
                "country": "BEL",
                "coordinates": {"latitude": "51.047599", "longitude": "3.729944"},
                "evse_uid": "3256",
                "evse_id": "BE*BEC*E041503001",
                "connector_id": "1",
                "connector_standard": "IEC_62196_T2",
                "connector_format": "SOCKET",
                "connector_power_type": "AC_3_PHASE"
            },
            "currency": "EUR",
            "charging_periods": [
                {
                    "start_date_time": "2015-06-29T21:39:09Z",
                    "dimensions": [{"type": "ENERGY", "volume": 120.0}]
                }
            ],
            "total_cost": {"excl_vat": 4.00},
            "total_energy": 120.0,
            "total_time": 1.973,
            "last_updated": "2015-06-29T23:37:32Z"
        }"#;
        let cdr: Cdr = serde_json::from_str(json).unwrap();
        assert_eq!(cdr.id.as_str(), "12345");
        assert_eq!(cdr.auth_method, AuthMethod::Whitelist);
        assert_eq!(
            cdr.cdr_location.connector_standard,
            ConnectorType::Iec62196T2
        );
        assert_eq!(cdr.cdr_location.connector_format, ConnectorFormat::Socket);
        assert_eq!(cdr.cdr_location.connector_power_type, PowerType::Ac3Phase);
        assert_eq!(cdr.charging_periods.len(), 1);
        assert_eq!(
            cdr.charging_periods[0].dimensions[0].dimension_type,
            CdrDimensionType::Energy
        );
        assert!((cdr.total_energy - 120.0).abs() < f64::EPSILON);
        assert!(cdr.credit.is_none());
        assert!(cdr.tariffs.is_empty());
    }

    // ── Tariff tests ──────────────────────────────────────────────────────────

    #[test]
    fn tariff_type_serde_screaming_snake() {
        assert_eq!(
            serde_json::to_string(&TariffType::AdHocPayment).unwrap(),
            "\"AD_HOC_PAYMENT\""
        );
        assert_eq!(
            serde_json::to_string(&TariffType::Regular).unwrap(),
            "\"REGULAR\""
        );
        assert_eq!(
            serde_json::from_str::<TariffType>("\"PROFILE_CHEAP\"").unwrap(),
            TariffType::ProfileCheap
        );
    }

    #[test]
    fn tariff_dimension_type_serde() {
        assert_eq!(
            serde_json::to_string(&TariffDimensionType::Energy).unwrap(),
            "\"ENERGY\""
        );
        assert_eq!(
            serde_json::to_string(&TariffDimensionType::ParkingTime).unwrap(),
            "\"PARKING_TIME\""
        );
        let t: TariffDimensionType = serde_json::from_str("\"FLAT\"").unwrap();
        assert_eq!(t, TariffDimensionType::Flat);
    }

    #[test]
    fn day_of_week_serde() {
        assert_eq!(
            serde_json::to_string(&DayOfWeek::Monday).unwrap(),
            "\"MONDAY\""
        );
        assert_eq!(
            serde_json::from_str::<DayOfWeek>("\"SATURDAY\"").unwrap(),
            DayOfWeek::Saturday
        );
    }

    #[test]
    fn reservation_restriction_type_serde() {
        assert_eq!(
            serde_json::to_string(&ReservationRestrictionType::ReservationExpires).unwrap(),
            "\"RESERVATION_EXPIRES\""
        );
        assert_eq!(
            serde_json::from_str::<ReservationRestrictionType>("\"RESERVATION\"").unwrap(),
            ReservationRestrictionType::Reservation
        );
    }

    #[test]
    fn price_component_type_field_renamed() {
        let pc = PriceComponent {
            component_type: TariffDimensionType::Energy,
            price: 0.25,
            vat: Some(21.0),
            step_size: 1,
        };
        let json = serde_json::to_string(&pc).unwrap();
        assert!(
            json.contains("\"type\":\"ENERGY\""),
            "wire name must be 'type': {json}"
        );
        assert!(
            !json.contains("component_type"),
            "Rust field name must not appear: {json}"
        );

        let back: PriceComponent = serde_json::from_str(&json).unwrap();
        assert_eq!(back.component_type, TariffDimensionType::Energy);
        assert!((back.price - 0.25).abs() < f64::EPSILON);
        assert_eq!(back.step_size, 1);
    }

    #[test]
    fn price_component_vat_omitted_when_none() {
        let pc = PriceComponent {
            component_type: TariffDimensionType::Flat,
            price: 1.00,
            vat: None,
            step_size: 1,
        };
        let json = serde_json::to_string(&pc).unwrap();
        assert!(
            !json.contains("vat"),
            "vat must be omitted when None: {json}"
        );
    }

    #[test]
    fn tariff_element_roundtrip() {
        let te = TariffElement {
            price_components: vec![PriceComponent {
                component_type: TariffDimensionType::Time,
                price: 2.00,
                vat: None,
                step_size: 300,
            }],
            restrictions: Some(TariffRestrictions {
                day_of_week: vec![DayOfWeek::Monday, DayOfWeek::Tuesday],
                min_duration: Some(1800),
                ..TariffRestrictions::default()
            }),
        };
        let json = serde_json::to_string(&te).unwrap();
        let back: TariffElement = serde_json::from_str(&json).unwrap();
        assert_eq!(te, back);
    }

    #[test]
    fn tariff_restrictions_empty_omits_fields() {
        let tr = TariffRestrictions::default();
        let json = serde_json::to_string(&tr).unwrap();
        assert_eq!(json, "{}");
    }

    #[test]
    fn tariff_type_field_renamed_and_optional() {
        let t = Tariff {
            country_code: CiString2::try_from("NL").unwrap(),
            party_id: CiString3::try_from("ALL").unwrap(),
            id: CiString36::try_from("12").unwrap(),
            currency: "EUR".to_string(),
            tariff_type: Some(TariffType::Regular),
            tariff_alt_text: vec![],
            tariff_alt_url: None,
            min_price: None,
            max_price: None,
            elements: vec![TariffElement {
                price_components: vec![PriceComponent {
                    component_type: TariffDimensionType::Energy,
                    price: 0.30,
                    vat: None,
                    step_size: 1,
                }],
                restrictions: None,
            }],
            start_date_time: None,
            end_date_time: None,
            energy_mix: None,
            last_updated: "2019-01-14T08:00:00Z".parse().unwrap(),
        };
        let json = serde_json::to_string(&t).unwrap();
        assert!(
            json.contains("\"type\":\"REGULAR\""),
            "wire name must be 'type': {json}"
        );
        assert!(
            !json.contains("tariff_type"),
            "Rust field must not appear: {json}"
        );

        let back: Tariff = serde_json::from_str(&json).unwrap();
        assert_eq!(back.tariff_type, Some(TariffType::Regular));
    }

    #[test]
    fn tariff_type_omitted_when_none() {
        let t = Tariff {
            country_code: CiString2::try_from("NL").unwrap(),
            party_id: CiString3::try_from("ALL").unwrap(),
            id: CiString36::try_from("12").unwrap(),
            currency: "EUR".to_string(),
            tariff_type: None,
            tariff_alt_text: vec![],
            tariff_alt_url: None,
            min_price: None,
            max_price: None,
            elements: vec![],
            start_date_time: None,
            end_date_time: None,
            energy_mix: None,
            last_updated: "2019-01-14T08:00:00Z".parse().unwrap(),
        };
        let json = serde_json::to_string(&t).unwrap();
        assert!(
            !json.contains("\"type\""),
            "type must be omitted when None: {json}"
        );
    }

    #[test]
    fn tariff_spec_example_roundtrip() {
        // Example from OCPI 2.2.1 mod_tariffs.asciidoc §Example
        let json = r#"{
            "country_code": "DE",
            "party_id": "ALL",
            "id": "ALLPOW2",
            "currency": "EUR",
            "elements": [
                {
                    "price_components": [
                        {"type": "FLAT", "price": 0.00, "step_size": 1},
                        {"type": "TIME", "price": 2.00, "step_size": 300}
                    ]
                }
            ],
            "last_updated": "2018-12-05T10:04:04Z"
        }"#;
        let tariff: Tariff = serde_json::from_str(json).unwrap();
        assert_eq!(tariff.id.as_str(), "ALLPOW2");
        assert_eq!(tariff.currency, "EUR");
        assert!(tariff.tariff_type.is_none());
        assert_eq!(tariff.elements.len(), 1);
        assert_eq!(tariff.elements[0].price_components.len(), 2);
        assert_eq!(
            tariff.elements[0].price_components[0].component_type,
            TariffDimensionType::Flat
        );
        assert_eq!(
            tariff.elements[0].price_components[1].component_type,
            TariffDimensionType::Time
        );
        assert!((tariff.elements[0].price_components[1].price - 2.00).abs() < f64::EPSILON);
        assert_eq!(tariff.elements[0].price_components[1].step_size, 300);
    }
}
