//! OCPI **2.2.1** typed models (the primary production target).
//!
//! Modules: Versions, Credentials, Locations, Sessions, CDRs, Tariffs, Tokens,
//! Commands, ChargingProfiles, HubClientInfo.
//!
//! Populated incrementally — see milestones **M2–M6** in the roadmap.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::common::{BusinessDetails, CiString2, CiString3, CiString36, Price, Role, Url};
use crate::OcpiError;

// ── CredentialsRole ───────────────────────────────────────────────────────────

/// A single role entry in a [`Credentials`] object.
///
/// Every role needs a unique combination of `role`, `party_id`, and
/// `country_code`. A platform that provides white-label CPO services may
/// carry multiple `CredentialsRole` entries — the schema is forward-compatible
/// with that use-case even though the current server implementation only
/// handles single-role registrations.
///
/// Spec: `specs/ocpi/2.2.1/credentials.asciidoc` — CredentialsRole class.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CredentialsRole {
    /// The role this party fulfils in the OCPI ecosystem.
    pub role: Role,
    /// Business details about this party.
    pub business_details: BusinessDetails,
    /// eMI3 party identifier (3-char, e.g. `"EXA"`).
    pub party_id: CiString3,
    /// ISO 3166-1 alpha-2 country code (e.g. `"NL"`).
    pub country_code: CiString2,
}

// ── Credentials ───────────────────────────────────────────────────────────────

/// The credentials object exchanged during OCPI registration (POST) and
/// updates (PUT), and returned on GET.
///
/// `roles` must be non-empty; multi-role is schema-legal per the spec.
/// Server implementations that have not yet added multi-role support
/// should call [`Credentials::check_single_role`] and return
/// [`OcpiStatusCode::ServerError`](crate::OcpiStatusCode::ServerError) on
/// failure.
///
/// Spec: `specs/ocpi/2.2.1/credentials.asciidoc` — Credentials object.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Credentials {
    /// Bearer token the remote party must use in subsequent requests.
    ///
    /// OCPI 2.2.1 spec: printable non-whitespace ASCII (U+0021–U+007E),
    /// max 64 characters. Not validated here — callers are responsible.
    pub token: String,
    /// URL of this party's `/versions` endpoint.
    pub url: Url,
    /// Roles this party provides. Non-empty; one entry is the common case.
    pub roles: Vec<CredentialsRole>,
}

impl Credentials {
    /// Returns `Err` when `roles` is empty (spec requires at least one).
    ///
    /// # Errors
    ///
    /// Returns [`OcpiError::Invalid`] if `roles` is empty.
    pub fn validate(&self) -> Result<(), OcpiError> {
        if self.roles.is_empty() {
            return Err(OcpiError::Invalid(
                "credentials.roles must contain at least one entry".into(),
            ));
        }
        Ok(())
    }

    /// Returns `Err` when `roles` has more than one entry.
    ///
    /// Call this in server implementations that have not yet added multi-role
    /// support; return [`OcpiStatusCode::ServerError`](crate::OcpiStatusCode::ServerError)
    /// to the remote party so it knows the limitation is server-side.
    ///
    /// # Errors
    ///
    /// Returns [`OcpiError::Invalid`] if `roles.len() > 1`.
    pub fn check_single_role(&self) -> Result<(), OcpiError> {
        if self.roles.len() > 1 {
            return Err(OcpiError::Invalid(
                "multi-role credentials are not yet supported by this server".into(),
            ));
        }
        Ok(())
    }
}

// ── TokenType ─────────────────────────────────────────────────────────────────

/// Type of RFID/app token used to start a session or CDR.
///
/// Forward reference — full definition lives in the Tokens module (M5).
///
/// Spec: `specs/ocpi/2.2.1/mod_tokens.asciidoc` — TokenType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TokenType {
    /// One-time-use token generated by a server or app (single session binding).
    AdHocUser,
    /// Persistent app-generated token (same user, same token every session).
    AppUser,
    /// Other token type.
    Other,
    /// RFID token read by the charge point reader.
    Rfid,
}

// ── AuthMethod ────────────────────────────────────────────────────────────────

/// Method used for authentication during a charging session or CDR.
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — AuthMethod enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AuthMethod {
    /// Authentication request was sent to the eMSP.
    AuthRequest,
    /// A Command (StartSession or ReserveNow) was used; its token was the authorization.
    Command,
    /// Whitelist was used; no real-time eMSP request was performed.
    Whitelist,
}

// ── CdrToken ──────────────────────────────────────────────────────────────────

/// Compact token record embedded in a Session or CDR.
///
/// Contains the minimum information needed to identify the token that started
/// the session. Does not include display-only fields like `visual_number` —
/// those live in the full `Token` object (Tokens module, M5).
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — CdrToken class.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CdrToken {
    /// ISO 3166-1 alpha-2 country code of the eMSP that owns this token.
    pub country_code: CiString2,
    /// Party ID of the eMSP that owns this token.
    pub party_id: CiString3,
    /// Unique identifier of the token (e.g. the RFID card UID).
    pub uid: CiString36,
    /// Type of the token.
    #[serde(rename = "type")]
    pub token_type: TokenType,
    /// Contract ID (eMA ID) of the EV driver within the eMSP's platform.
    pub contract_id: CiString36,
}

// ── CdrDimensionType ──────────────────────────────────────────────────────────

/// Measurement dimension type for a charging period.
///
/// Values marked *session-only* are valid in `Session.charging_periods` but
/// SHALL NOT appear in CDR `charging_periods`.
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — CdrDimensionType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CdrDimensionType {
    /// Average charging current (A). Session-only.
    Current,
    /// Total energy (dis-)charged (kWh).
    Energy,
    /// Total energy fed back into the grid (kWh). Session-only.
    EnergyExport,
    /// Total energy charged from the grid (kWh). Session-only.
    EnergyImport,
    /// Sum of maximum current over all phases (A).
    MaxCurrent,
    /// Sum of minimum current over all phases (A).
    MinCurrent,
    /// Maximum power reached (kW).
    MaxPower,
    /// Minimum power reached (kW).
    MinPower,
    /// Time the vehicle was not requesting power (hours).
    ParkingTime,
    /// Average power (kW). Session-only.
    Power,
    /// Time the EVSE was reserved and idle (hours).
    ReservationTime,
    /// Current state of charge of the EV (0–100 %). Session-only.
    StateOfCharge,
    /// Time actively charging (hours).
    Time,
}

// ── CdrDimension ──────────────────────────────────────────────────────────────

/// A single measured dimension within a [`ChargingPeriod`].
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — CdrDimension class.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CdrDimension {
    /// The dimension type.
    #[serde(rename = "type")]
    pub dimension_type: CdrDimensionType,
    /// Volume consumed, in the unit defined by `dimension_type`.
    pub volume: f64,
}

// ── ChargingPeriod ────────────────────────────────────────────────────────────

/// A contiguous sub-interval of a charging session with associated dimension
/// measurements. Shared between Sessions and CDRs.
///
/// Spec: `specs/ocpi/2.2.1/mod_cdrs.asciidoc` — ChargingPeriod class.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChargingPeriod {
    /// Start of this period. The period ends when the next period begins (or
    /// the session ends if this is the last period).
    pub start_date_time: DateTime<Utc>,
    /// Dimension measurements active during this period.
    pub dimensions: Vec<CdrDimension>,
    /// Tariff ID applicable to this period, if any.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tariff_id: Option<CiString36>,
}

// ── SessionStatus ─────────────────────────────────────────────────────────────

/// State of a charging session.
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — SessionStatus enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SessionStatus {
    /// Session accepted and active; EV is (or can be) charging.
    Active,
    /// Session finished. No further updates will be sent.
    Completed,
    /// Session declared invalid; will not be billed.
    Invalid,
    /// Session pending; not all pre-conditions met yet.
    Pending,
    /// Session started by a reservation; actual charging has not begun.
    Reservation,
}

// ── ProfileType ───────────────────────────────────────────────────────────────

/// Smart-charging profile preference set by the EV driver.
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — ProfileType enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ProfileType {
    /// Driver prefers the cheapest available charging profile.
    Cheap,
    /// Driver wants maximum charging speed; willing to pay a premium.
    Fast,
    /// Driver prefers the greenest (most renewable) energy.
    Green,
    /// Driver has no special preferences.
    Regular,
}

// ── ChargingPreferencesResponse ───────────────────────────────────────────────

/// Response to a `PUT /sessions/{id}/charging_preferences` request.
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — ChargingPreferencesResponse enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ChargingPreferencesResponse {
    /// Preferences accepted; EVSE will try to fulfil them.
    Accepted,
    /// CPO requires `departure_time` to apply smart charging.
    DepartureRequired,
    /// CPO requires `energy_need` to apply smart charging.
    EnergyNeedRequired,
    /// The EVSE cannot fulfil the requested preferences.
    NotPossible,
    /// The requested `profile_type` is not supported by the EVSE.
    ProfileTypeNotSupported,
}

// ── ChargingPreferences ───────────────────────────────────────────────────────

/// Driver charging preferences sent to the CPO during an active session.
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — ChargingPreferences object.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChargingPreferences {
    /// Desired smart-charging profile.
    pub profile_type: ProfileType,
    /// Expected departure time (driver estimate; not a guarantee).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub departure_time: Option<DateTime<Utc>>,
    /// Requested energy in kWh to charge before `departure_time`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub energy_need: Option<f64>,
    /// Whether the driver allows vehicle-to-grid (V2G) discharging.
    /// Defaults to `false` when absent.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub discharge_allowed: Option<bool>,
}

// ── Session ───────────────────────────────────────────────────────────────────

/// A charging session object owned by the CPO.
///
/// Describes one charging session from start to finish, including token,
/// location references, energy consumed, and cost. Transmitted from CPO
/// to eMSP via push (PUT/PATCH) or pull (GET list).
///
/// Spec: `specs/ocpi/2.2.1/mod_sessions.asciidoc` — Session object.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Session {
    /// ISO 3166-1 alpha-2 country code of the CPO that owns this session.
    pub country_code: CiString2,
    /// Party ID of the CPO that owns this session.
    pub party_id: CiString3,
    /// Unique session ID within the CPO's platform.
    pub id: CiString36,
    /// Timestamp when the session became ACTIVE (or was created if PENDING).
    pub start_date_time: DateTime<Utc>,
    /// Timestamp when the session ended. `None` if still active.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub end_date_time: Option<DateTime<Utc>>,
    /// Total energy charged so far, in kWh.
    pub kwh: f64,
    /// Token used to start the session.
    pub cdr_token: CdrToken,
    /// Authentication method used (may change during the session).
    pub auth_method: AuthMethod,
    /// Authorization reference from the eMSP (e.g. from StartSession).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub authorization_reference: Option<CiString36>,
    /// `Location.id` of the CPO location where this session is happening.
    pub location_id: CiString36,
    /// `EVSE.uid` at the location (`#NA` for reservation without EVSE assignment).
    pub evse_uid: CiString36,
    /// `Connector.id` at the EVSE (`#NA` for reservation without connector assignment).
    pub connector_id: CiString36,
    /// Optional meter identifier inside the charge point.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub meter_id: Option<String>,
    /// ISO 4217 currency code (e.g. `"EUR"`).
    pub currency: String,
    /// Charging periods recorded so far (may be empty if no periods yet).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub charging_periods: Vec<ChargingPeriod>,
    /// Total cost of the session so far in `currency`. `None` if not yet known.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub total_cost: Option<Price>,
    /// Current status of the session.
    pub status: SessionStatus,
    /// Timestamp of the last update (or creation) of this session object.
    pub last_updated: DateTime<Utc>,
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::common::BusinessDetails;

    fn make_role(role: Role, party: &str, country: &str) -> CredentialsRole {
        CredentialsRole {
            role,
            business_details: BusinessDetails {
                name: "Test Party".into(),
                website: None,
                logo: None,
            },
            party_id: CiString3::try_from(party).unwrap(),
            country_code: CiString2::try_from(country).unwrap(),
        }
    }

    fn cpo_credentials() -> Credentials {
        Credentials {
            token: "TOKEN_B".into(),
            url: Url::try_from("https://example.com/ocpi/versions").unwrap(),
            roles: vec![make_role(Role::Cpo, "EXA", "NL")],
        }
    }

    // ── Serde round-trips ─────────────────────────────────────────────────────

    #[test]
    fn credentials_serde_roundtrip() {
        let c = cpo_credentials();
        let json = serde_json::to_string(&c).unwrap();
        let back: Credentials = serde_json::from_str(&json).unwrap();
        assert_eq!(back, c);
    }

    #[test]
    fn credentials_role_serde_roundtrip() {
        let r = make_role(Role::Emsp, "MSP", "DE");
        let json = serde_json::to_string(&r).unwrap();
        let back: CredentialsRole = serde_json::from_str(&json).unwrap();
        assert_eq!(back, r);
    }

    /// Spec example: minimal CPO credentials object.
    #[test]
    fn credentials_spec_example_minimal_cpo() {
        let json = r#"{
            "token": "ZXhhbXBsZS10b2tlbgo=",
            "url": "https://example.com/ocpi/versions",
            "roles": [
                {
                    "role": "CPO",
                    "business_details": {"name": "Example CPO"},
                    "party_id": "EXA",
                    "country_code": "NL"
                }
            ]
        }"#;
        let c: Credentials = serde_json::from_str(json).unwrap();
        assert_eq!(c.token, "ZXhhbXBsZS10b2tlbgo=");
        assert_eq!(c.roles.len(), 1);
        assert_eq!(c.roles[0].role, Role::Cpo);
        assert_eq!(c.roles[0].party_id.as_str(), "EXA");
        assert_eq!(c.roles[0].country_code.as_str(), "NL");
        assert_eq!(c.roles[0].business_details.name, "Example CPO");
    }

    /// Spec example: combined CPO + eMSP credentials (multi-role, schema-legal).
    #[test]
    fn credentials_spec_example_multi_role() {
        let json = r#"{
            "token": "TOKEN_C",
            "url": "https://example.com/ocpi/versions",
            "roles": [
                {
                    "role": "CPO",
                    "business_details": {"name": "Example Operator"},
                    "party_id": "EXA",
                    "country_code": "NL"
                },
                {
                    "role": "EMSP",
                    "business_details": {"name": "Example Provider"},
                    "party_id": "EXB",
                    "country_code": "NL"
                }
            ]
        }"#;
        let c: Credentials = serde_json::from_str(json).unwrap();
        assert_eq!(c.roles.len(), 2);
        assert_eq!(c.roles[0].role, Role::Cpo);
        assert_eq!(c.roles[1].role, Role::Emsp);
    }

    // ── Validation ────────────────────────────────────────────────────────────

    #[test]
    fn validate_rejects_empty_roles() {
        let c = Credentials {
            token: "T".into(),
            url: Url::try_from("https://example.com/ocpi/versions").unwrap(),
            roles: vec![],
        };
        assert!(c.validate().is_err());
    }

    #[test]
    fn validate_accepts_single_role() {
        assert!(cpo_credentials().validate().is_ok());
    }

    #[test]
    fn check_single_role_rejects_multi_role() {
        let json = r#"{
            "token": "T",
            "url": "https://example.com/ocpi/versions",
            "roles": [
                {"role":"CPO","business_details":{"name":"A"},"party_id":"AAA","country_code":"NL"},
                {"role":"EMSP","business_details":{"name":"B"},"party_id":"BBB","country_code":"NL"}
            ]
        }"#;
        let c: Credentials = serde_json::from_str(json).unwrap();
        assert!(c.check_single_role().is_err());
    }

    #[test]
    fn check_single_role_accepts_single() {
        assert!(cpo_credentials().check_single_role().is_ok());
    }

    // ── TokenType ─────────────────────────────────────────────────────────────

    #[test]
    fn token_type_serde_screaming_snake() {
        assert_eq!(
            serde_json::to_string(&TokenType::AdHocUser).unwrap(),
            "\"AD_HOC_USER\""
        );
        assert_eq!(
            serde_json::to_string(&TokenType::AppUser).unwrap(),
            "\"APP_USER\""
        );
        assert_eq!(serde_json::to_string(&TokenType::Rfid).unwrap(), "\"RFID\"");
        assert_eq!(
            serde_json::to_string(&TokenType::Other).unwrap(),
            "\"OTHER\""
        );
    }

    #[test]
    fn token_type_roundtrip() {
        for tt in [
            TokenType::AdHocUser,
            TokenType::AppUser,
            TokenType::Other,
            TokenType::Rfid,
        ] {
            let json = serde_json::to_string(&tt).unwrap();
            let back: TokenType = serde_json::from_str(&json).unwrap();
            assert_eq!(back, tt);
        }
    }

    // ── AuthMethod ────────────────────────────────────────────────────────────

    #[test]
    fn auth_method_serde_screaming_snake() {
        assert_eq!(
            serde_json::to_string(&AuthMethod::AuthRequest).unwrap(),
            "\"AUTH_REQUEST\""
        );
        assert_eq!(
            serde_json::to_string(&AuthMethod::Command).unwrap(),
            "\"COMMAND\""
        );
        assert_eq!(
            serde_json::to_string(&AuthMethod::Whitelist).unwrap(),
            "\"WHITELIST\""
        );
    }

    #[test]
    fn auth_method_roundtrip() {
        for am in [
            AuthMethod::AuthRequest,
            AuthMethod::Command,
            AuthMethod::Whitelist,
        ] {
            let json = serde_json::to_string(&am).unwrap();
            let back: AuthMethod = serde_json::from_str(&json).unwrap();
            assert_eq!(back, am);
        }
    }

    // ── CdrToken ──────────────────────────────────────────────────────────────

    fn make_cdr_token() -> CdrToken {
        CdrToken {
            country_code: CiString2::try_from("NL").unwrap(),
            party_id: CiString3::try_from("TNM").unwrap(),
            uid: CiString36::try_from("012345678").unwrap(),
            token_type: TokenType::Rfid,
            contract_id: CiString36::try_from("NL8ACC12E46L89").unwrap(),
        }
    }

    #[test]
    fn cdr_token_serde_roundtrip() {
        let t = make_cdr_token();
        let json = serde_json::to_string(&t).unwrap();
        // field must be named "type" on the wire
        assert!(json.contains("\"type\""));
        let back: CdrToken = serde_json::from_str(&json).unwrap();
        assert_eq!(back, t);
    }

    #[test]
    fn cdr_token_deserialize_from_spec_example() {
        let json = r#"{
            "country_code": "NL",
            "party_id": "TNM",
            "uid": "012345678",
            "type": "RFID",
            "contract_id": "NL8ACC12E46L89"
        }"#;
        let t: CdrToken = serde_json::from_str(json).unwrap();
        assert_eq!(t.token_type, TokenType::Rfid);
        assert_eq!(t.uid.as_str(), "012345678");
    }

    // ── CdrDimensionType / CdrDimension ───────────────────────────────────────

    #[test]
    fn cdr_dimension_type_serde() {
        assert_eq!(
            serde_json::to_string(&CdrDimensionType::Energy).unwrap(),
            "\"ENERGY\""
        );
        assert_eq!(
            serde_json::to_string(&CdrDimensionType::StateOfCharge).unwrap(),
            "\"STATE_OF_CHARGE\""
        );
        assert_eq!(
            serde_json::to_string(&CdrDimensionType::ParkingTime).unwrap(),
            "\"PARKING_TIME\""
        );
    }

    #[test]
    fn cdr_dimension_serde_roundtrip() {
        let d = CdrDimension {
            dimension_type: CdrDimensionType::Energy,
            volume: 15.342,
        };
        let json = serde_json::to_string(&d).unwrap();
        assert!(json.contains("\"type\""));
        let back: CdrDimension = serde_json::from_str(&json).unwrap();
        assert!((back.volume - 15.342).abs() < f64::EPSILON);
        assert_eq!(back.dimension_type, CdrDimensionType::Energy);
    }

    // ── ChargingPeriod ────────────────────────────────────────────────────────

    #[test]
    fn charging_period_serde_roundtrip() {
        let p = ChargingPeriod {
            start_date_time: chrono::DateTime::parse_from_rfc3339("2015-06-29T22:39:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
            dimensions: vec![CdrDimension {
                dimension_type: CdrDimensionType::Energy,
                volume: 0.0,
            }],
            tariff_id: None,
        };
        let json = serde_json::to_string(&p).unwrap();
        assert!(!json.contains("tariff_id"));
        let back: ChargingPeriod = serde_json::from_str(&json).unwrap();
        assert_eq!(back, p);
    }

    #[test]
    fn charging_period_with_tariff_id_roundtrip() {
        let p = ChargingPeriod {
            start_date_time: chrono::DateTime::parse_from_rfc3339("2015-06-29T22:39:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
            dimensions: vec![CdrDimension {
                dimension_type: CdrDimensionType::Time,
                volume: 1.5,
            }],
            tariff_id: Some(CiString36::try_from("12").unwrap()),
        };
        let json = serde_json::to_string(&p).unwrap();
        assert!(json.contains("\"tariff_id\""));
        let back: ChargingPeriod = serde_json::from_str(&json).unwrap();
        assert_eq!(back, p);
    }

    // ── SessionStatus / ProfileType / ChargingPreferencesResponse ─────────────

    #[test]
    fn session_status_serde() {
        assert_eq!(
            serde_json::to_string(&SessionStatus::Active).unwrap(),
            "\"ACTIVE\""
        );
        assert_eq!(
            serde_json::to_string(&SessionStatus::Completed).unwrap(),
            "\"COMPLETED\""
        );
        assert_eq!(
            serde_json::to_string(&SessionStatus::Reservation).unwrap(),
            "\"RESERVATION\""
        );
    }

    #[test]
    fn profile_type_serde() {
        assert_eq!(
            serde_json::to_string(&ProfileType::Cheap).unwrap(),
            "\"CHEAP\""
        );
        assert_eq!(
            serde_json::to_string(&ProfileType::Fast).unwrap(),
            "\"FAST\""
        );
        assert_eq!(
            serde_json::to_string(&ProfileType::Green).unwrap(),
            "\"GREEN\""
        );
        assert_eq!(
            serde_json::to_string(&ProfileType::Regular).unwrap(),
            "\"REGULAR\""
        );
    }

    #[test]
    fn charging_preferences_response_serde() {
        assert_eq!(
            serde_json::to_string(&ChargingPreferencesResponse::ProfileTypeNotSupported).unwrap(),
            "\"PROFILE_TYPE_NOT_SUPPORTED\""
        );
        assert_eq!(
            serde_json::to_string(&ChargingPreferencesResponse::DepartureRequired).unwrap(),
            "\"DEPARTURE_REQUIRED\""
        );
    }

    // ── ChargingPreferences ───────────────────────────────────────────────────

    #[test]
    fn charging_preferences_serde_roundtrip() {
        let p = ChargingPreferences {
            profile_type: ProfileType::Green,
            departure_time: None,
            energy_need: Some(40.0),
            discharge_allowed: Some(false),
        };
        let json = serde_json::to_string(&p).unwrap();
        assert!(!json.contains("departure_time"));
        let back: ChargingPreferences = serde_json::from_str(&json).unwrap();
        assert_eq!(back, p);
    }

    #[test]
    fn charging_preferences_minimal_roundtrip() {
        let json = r#"{"profile_type":"CHEAP"}"#;
        let p: ChargingPreferences = serde_json::from_str(json).unwrap();
        assert_eq!(p.profile_type, ProfileType::Cheap);
        assert!(p.departure_time.is_none());
        assert!(p.energy_need.is_none());
        assert!(p.discharge_allowed.is_none());
    }

    // ── Session ───────────────────────────────────────────────────────────────

    fn make_session() -> Session {
        Session {
            country_code: CiString2::try_from("NL").unwrap(),
            party_id: CiString3::try_from("TNM").unwrap(),
            id: CiString36::try_from("101").unwrap(),
            start_date_time: chrono::DateTime::parse_from_rfc3339("2020-03-09T10:17:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
            end_date_time: None,
            kwh: 0.0,
            cdr_token: make_cdr_token(),
            auth_method: AuthMethod::Whitelist,
            authorization_reference: None,
            location_id: CiString36::try_from("LOC1").unwrap(),
            evse_uid: CiString36::try_from("3256").unwrap(),
            connector_id: CiString36::try_from("1").unwrap(),
            meter_id: None,
            currency: "EUR".into(),
            charging_periods: vec![],
            total_cost: None,
            status: SessionStatus::Pending,
            last_updated: chrono::DateTime::parse_from_rfc3339("2020-03-09T10:17:09Z")
                .unwrap()
                .with_timezone(&chrono::Utc),
        }
    }

    #[test]
    fn session_serde_roundtrip() {
        let s = make_session();
        let json = serde_json::to_string(&s).unwrap();
        let back: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(back, s);
    }

    #[test]
    fn session_optional_fields_absent_when_none() {
        let s = make_session();
        let json = serde_json::to_string(&s).unwrap();
        assert!(!json.contains("end_date_time"));
        assert!(!json.contains("authorization_reference"));
        assert!(!json.contains("meter_id"));
        assert!(!json.contains("charging_periods"));
        assert!(!json.contains("total_cost"));
    }

    #[test]
    fn session_deserialize_spec_example_simple_start() {
        // Based on the spec's "simple start" example (§Sessions module §Examples)
        let json = r#"{
            "country_code": "NL",
            "party_id": "TNM",
            "id": "101",
            "start_date_time": "2020-03-09T10:17:09Z",
            "kwh": 0.00,
            "cdr_token": {
                "country_code": "NL",
                "party_id": "TNM",
                "uid": "012345678",
                "type": "RFID",
                "contract_id": "NL8ACC12E46L89"
            },
            "auth_method": "WHITELIST",
            "location_id": "LOC1",
            "evse_uid": "3256",
            "connector_id": "1",
            "currency": "EUR",
            "status": "PENDING",
            "last_updated": "2020-03-09T10:17:09Z"
        }"#;
        let s: Session = serde_json::from_str(json).unwrap();
        assert_eq!(s.id.as_str(), "101");
        assert_eq!(s.status, SessionStatus::Pending);
        assert_eq!(s.auth_method, AuthMethod::Whitelist);
        assert_eq!(s.cdr_token.token_type, TokenType::Rfid);
        assert!(s.charging_periods.is_empty());
        assert!(s.total_cost.is_none());
    }

    #[test]
    fn session_deserialize_with_charging_period() {
        let json = r#"{
            "country_code": "NL",
            "party_id": "TNM",
            "id": "101",
            "start_date_time": "2020-03-09T10:17:09Z",
            "end_date_time": "2020-03-09T11:01:09Z",
            "kwh": 41.12,
            "cdr_token": {
                "country_code": "NL",
                "party_id": "TNM",
                "uid": "012345678",
                "type": "RFID",
                "contract_id": "NL8ACC12E46L89"
            },
            "auth_method": "WHITELIST",
            "location_id": "LOC1",
            "evse_uid": "3256",
            "connector_id": "1",
            "currency": "EUR",
            "charging_periods": [
                {
                    "start_date_time": "2020-03-09T10:17:09Z",
                    "dimensions": [
                        {"type": "ENERGY", "volume": 41.12}
                    ]
                }
            ],
            "total_cost": {"excl_vat": 8.50, "incl_vat": 9.35},
            "status": "COMPLETED",
            "last_updated": "2020-03-09T11:01:09Z"
        }"#;
        let s: Session = serde_json::from_str(json).unwrap();
        assert_eq!(s.status, SessionStatus::Completed);
        assert_eq!(s.charging_periods.len(), 1);
        assert_eq!(
            s.charging_periods[0].dimensions[0].dimension_type,
            CdrDimensionType::Energy
        );
        assert!(s.total_cost.is_some());
        assert!((s.kwh - 41.12).abs() < f64::EPSILON);
        assert!(s.end_date_time.is_some());
    }
}
